apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: api-server-daemon
  namespace: default
  labels:
    app: api-server-daemon
spec:
  selector:
    matchLabels:
      app: api-server-daemon
  template:
    metadata:
      labels:
        app: api-server-daemon
    spec:
      containers:
      - name: api-server-daemon
        image: zerotay/api-server:v1.0.0
        ports:
          - containerPort: 8080
        # resources:
        #   limits:
        #     memory: 200Mi
        #   requests:
        #     cpu: 100m
        #     memory: 200Mi
