apiVersion: v1
kind: Pod
metadata:
  name: failure-pod
spec:
  # initContainers:
  # - name: install
  #   image: alpine
  #   command: ["sh", "-c", "exit 1"]
  #   restartPolicy: Always
  containers:
  - name: failure
    image: alpine
    # command: ["sh", "-c", "exit 1"]
    command: ["sh", "-c", "while true; do sleep 3600; done"]
  # restartPolicy: OnFailure
  # restartPolicy: Never
  # restartPolicy: Always
