apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  shareProcessNamespace: true
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: netshoot
    image: nicolaka/netshoot
    # command: ["sh", "-c", "exit 1"]
    command: ["sh", "-c", "while true; do sleep 3600; done"]
