apiVersion: v1
kind: Pod
metadata:
  name: "readiness"
spec:
  readinessGates:
    - conditionType: "www.example.com/feature-1"
  containers:
  - name: readiness
    image: alpine
    ports:
    - containerPort: 80
      name: http
    command: ["sh", "-c", "while true; do sleep 3600; done"]
  restartPolicy: Always
---
