apiVersion: v1
kind: Pod
metadata:
  name: success-pod
spec:
  # initContainers:
  # - name: install
  #   image: alpine
  #   command: ["sh", "-c", "exit 1"]
  #   restartPolicy: Always
  containers:
  - name: success
    image: alpine
    # command: ["sh", "-c", "exit 1"]
    command: ["sh", "-c", "sleep 4"]
  # restartPolicy: OnFailure
  restartPolicy: Never
  # restartPolicy: Always

