apiVersion: v1
kind: Pod
metadata:
  name: init 
spec:
  initContainers:
  - name: init-1
    image: alpine
    # command: ["sh", "-c", "exit 1"]
    command: ["sh", "-c", "touch /opt/first"]
    volumeMounts:
      - name: data
        mountPath: /opt
  - name: init-2 # must be unique
    image: alpine
    command: ["sh", "-c", "echo second > /opt/first"]
    # restartPolicy: Always
    volumeMounts:
      - name: data
        mountPath: /opt
  containers:
  - name: main
    image: alpine
    # command: ["sh", "-c", "exit 1"]
    command: ["sh", "-c", "cat /opt/first; while true; do sleep 3600; done"]
    volumeMounts:
      - name: data
        mountPath: /opt
  volumes:
    - name: data
      emptyDir: {}
  # restartPolicy: OnFailure
  # restartPolicy: Never
  # restartPolicy: Always

