apiVersion: v1
kind: Service
metadata:
  labels:
    app: load
  name: metal-svc
spec:
  selector:
    app: load
  ports:
  - name: load
    port: 5678
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load
  name: metal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: load
  template:
    metadata:
      labels:
        app: load
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
