apiVersion: v1
kind: Service
metadata:
  name: loxi-svc
  annotations:
    loxilb.io/liveness: "yes"
    # loxilb.io/lbmode: "onearm"
spec:
  # externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: loxi-svc
  ports:
    - port: 80
      targetPort: 80 
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: tcp-onearm-test
  labels:
    what: loxi-svc
spec:
  containers:
    - name: tcp-onearm-test
      image: ghcr.io/loxilb-io/nginx:stable
      ports:
        - containerPort: 80
