apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-pv
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: 172.30.1.60/smb
    nodeStageSecretRef:
      name: smbcreds
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-pvc
  labels:
    app: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  volumeName: default-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: default
spec:
  containers:
    - name: test
      image: busybox:1.28
      command: ['sh', '-c', 'echo "The app is running!" && tail -f /dev/null']
      volumeMounts:
        - name: pvc
          mountPath: /test
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: default-pvc
