apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: only-pvc
  labels:
    app: only
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  volumeName: only-pv
  storageClassName: local
