apiVersion: v1
kind: Pod
metadata:
  name: only-pod
spec:
  containers:
    - name: test
      image: busybox:1.28
      command: ['sh', '-c', 'echo "The app is running!" && tail -f /dev/null']
      volumeMounts:
        - name: pvc
          mountPath: /test
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: only-pvc
