apiVersion: v1
kind: Service
metadata:
  name: subdir-nfs
  namespace: default
spec:
  selector:
    app: subdir-nfs
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
---
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: subdir-nfs
  namespace: default
  labels:
    app: subdir-nfs
spec:
  selector:
    matchLabels:
      app: subdir-nfs
  replicas: 3
  template:
    metadata:
      labels:
        app: subdir-nfs
    spec:
      containers:
      - name: subdir-nfs
        image: nginx:1.16
        livenessProbe:
          tcpSocket:
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        ports:
        - containerPort: 80
          name: subdir-nfs
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: subdir-nfs
      volumes:
        - name: subdir-nfs
          persistentVolumeClaim:
            claimName: pvc-nfs-subdir
---


