apiVersion: v1
kind: Pod
metadata:
  name: readiness
  labels:
    test: readiness
spec:
  containers:
  - name: readiness
    image: registry.k8s.io/busybox
    args:
      - /bin/sh
      - -c
      - while true; do touch /tmp/healthy; sleep 5; rm -f /tmp/healthy; sleep 5; done
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      # initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 1 # default 3


