apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-svc
  name: my-svc
spec:
  selector:
    app: my-svc
  ports:
  - name: 5678-80
    port: 5678
    protocol: TCP
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-svc
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
