apiVersion: v1
kind: Service
metadata:
  labels:
    app: multi
  name: multi
spec:
  selector:
    app: multi
  ports:
  - name: 5678-80
    port: 5678
    protocol: TCP
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multi
  name: multi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi
  template:
    metadata:
      labels:
        app: multi
    spec:
      containers:
      - image: nginx:1.14.2
        name: multi
        ports:
        - containerPort: 80
