apiVersion: batch/v1
kind: Job
metadata:
  name: indexed
spec:
  template:
    spec:
      containers:
      - name: test
        image: python
        command: 
        - python3
        - -c
        - |
          import os, sys, time, random
          print(os.environ.get("JOB_COMPLETION_INDEX"))
          time.sleep(random.random())
          if int(os.environ.get("JOB_COMPLETION_INDEX")) % 2:
            sys.exit(1)   
          time.sleep(5)
        # - /bin/bash
        # - -c
        # - |
        #   if [ $JOB_COMPLETION_INDEX -ne 1 ];
        #   then
        #     exit 1
        #   fi
      restartPolicy: Never
  completions: 10
  completionMode: Indexed
  backoffLimitPerIndex: 1
  maxFailedIndexes: 2
  parallelism: 4
  backoffLimit: 7
