apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: inno-db
spec:
  secretName: root-info
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 1
  # datadirVolumeClaimTemplate:
  #   accessModes: 
  #     - ReadWriteOnce
  #   resources:
  #     requests:
  #       storage: 5Gi
  #   storageClassName: standard
  # initDB:
  #   clone:
  #     donorUrl: mycluster-0.mycluster-instances.another.svc.cluster.local:3306
  #     rootUser: root
  #     secretKeyRef:
  #       name: root-info
